/*
 * CentiScaPeHelp.java
 *
 * Created on 18 gennaio 2008, 12.30
 */
package org.cytoscape.centiscape.internal;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import org.cytoscape.application.CyApplicationManager;
import org.cytoscape.model.CyNetwork;
import org.cytoscape.model.CyNode;
import org.cytoscape.model.CyRow;

/**
 *
 * @author scardoni
 */
public class CentralitiesTable extends javax.swing.JFrame {

    private String helpString;
    public CyApplicationManager cyApplicationManager;
    public List<CyNetwork> networks=new ArrayList<CyNetwork>();
    public ArrayList<CyNode> node;
    ArrayList <String> centralityNames;

    /**
     * Creates new form CentiScaPeHelp
     */
    public CentralitiesTable(List <CyNetwork> networks,ArrayList<CyNode> node,ArrayList <String> centralityNames) {
        this.node=node;
        this.networks=networks;
        this.centralityNames=centralityNames;
        initComponents();
        this.setSize(620, 300);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        int nodeSize=node.size();
        int networkSize=networks.size();
        int CentralitySize=centralityNames.size();
        String data[][]=new String[CentralitySize][networkSize+1];
        for (int j=0;j<CentralitySize;j++)
            {
                if(centralityNames.get(j).equals("Edge Betweenness Dir")|| centralityNames.get(j).equals("Edge Betweenness unDir"))
                {
                    continue;
                }
                  data[j]=new String[networkSize+1];
                  data[j][0]=centralityNames.get(j);

            }
        for(int i=0;i<networkSize;i++)
        {
            CyRow row=networks.get(i).getDefaultNodeTable().getRow(node.get(0).getSUID());
            Double value=row.get(centralityNames.get(0), Double.class);
            for(int k=1;k<nodeSize;k++)
            {
                if(value!=null)
                    break;
                
                row =networks.get(i).getDefaultNodeTable().getRow(node.get(k).getSUID());
                value=row.get(centralityNames.get(0), Double.class);
                
            }
            
           if(value!=null)
           {
                for (int j=0;j<CentralitySize;j++)
            {
                if(centralityNames.get(j).equals("Edge Betweenness Dir")|| centralityNames.get(j).equals("Edge Betweenness unDir"))
                {
                    continue;
                }
                    
                  Double d=row.get(centralityNames.get(j), Double.class);
                  data[j][i+1]=String.valueOf(d);
                  System.out.println(d + ""+centralityNames.get(j));

            }
           }
           else
               System.out.println("Not found");
           
        }
        
     
       Object a[]= networks.toArray();
       Object columns[]=new Object[networkSize+1];
       columns[0]="Centralities";
       for(int i=0;i<networkSize;i++)
           columns[i+1]=a[i];
        
        jScrollPane1 = new javax.swing.JScrollPane();
        CentrJTable=new JTable(data,columns);
        jScrollPane1.setViewportView(CentrJTable);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE).addContainerGap()));
        
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private JTable CentrJTable;
    // End of variables declaration//GEN-END:variables

    
    
}
